spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tasklist
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always #never
      continue-on-error: false
    # data-locations: classpath:demo_data.sql
security:
  jwt:
    secret: aGZiYmtiYWllYmNpZWFpZWJsZWNldWNlY2xhZWNhaWJlbGNhZWN3Q0VCV0VXSUM=
    access: 3600000
    refresh: 2592000000
